{% set name = "colored-traceback" %}
{% set version = "0.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colored-traceback-{{ version }}.tar.gz
  sha256: ecbc8e41f0712ea81931d7cd436b8beb9f3eff1595d2498f183e0ef69b56fe84

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - pygments
    - python >=2.7

test:
  imports:
    - colored_traceback
    - colored_traceback.always
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.github.com/staticshock/colored-traceback.py
  summary: Automatically color uncaught exception tracebacks
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
